//
//  StyleKitName.swift
//  ProjectName
//
//  Created by AuthorName on 11/29/16.
//  Copyright (c) 2016 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//





import UIKit

public class DialView: UIView {
    override public func draw(_ rect: CGRect) {
        Dial.drawCanvas1(dialAngle: -30)
    }
}

public class Dial: NSObject {

    //// Drawing Methods

    public class func drawCanvas1(dialAngle: CGFloat = -1) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Color Declarations
        let strokeColor = UIColor(red: 0.338, green: 0.338, blue: 0.338, alpha: 1.000)
        let fillColor = UIColor(red: 0.972, green: 0.359, blue: 0.359, alpha: 1.000)

        //// Group 2
        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.move(to: CGPoint(x: 243, y: 121.5))
        bezierPath.addCurve(to: CGPoint(x: 121.5, y: 0), controlPoint1: CGPoint(x: 243, y: 54.4), controlPoint2: CGPoint(x: 188.6, y: 0))
        bezierPath.addCurve(to: CGPoint(x: 0, y: 121.5), controlPoint1: CGPoint(x: 54.4, y: 0), controlPoint2: CGPoint(x: 0, y: 54.4))
        bezierPath.addLine(to: CGPoint(x: 243, y: 121.5))
        bezierPath.close()
        strokeColor.setStroke()
        bezierPath.lineWidth = 2
        bezierPath.stroke()


        //// Bezier 2 Drawing
        context!.saveGState()
        context!.translateBy(x: 121.97, y: 119.41)
        context!.rotate(by: -dialAngle * CGFloat(M_PI) / 180)

        let bezier2Path = UIBezierPath()
        bezier2Path.move(to: CGPoint(x: -0.01, y: 4.19))
        bezier2Path.addCurve(to: CGPoint(x: -0.01, y: -119.41), controlPoint1: CGPoint(x: 13.38, y: 4.19), controlPoint2: CGPoint(x: -0.01, y: -119.41))
        bezier2Path.addCurve(to: CGPoint(x: -0.01, y: 4.19), controlPoint1: CGPoint(x: -0.01, y: -119.41), controlPoint2: CGPoint(x: -13.41, y: 4.19))
        bezier2Path.close()
        bezier2Path.usesEvenOddFillRule = true;

        fillColor.setFill()
        bezier2Path.fill()

        context!.restoreGState()
    }

}
